# Generated by Django 4.1 on 2022-09-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(null=True, upload_to='articulos'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.TextField(max_length=5000),
        ),
    ]
