# Generated by Django 4.1 on 2022-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_entrada_imagen_alter_entrada_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(max_length=50),
        ),
    ]
